version: '3.8'
services:
   react-app:
     image: react-app
     stdin_open: true
     ports: 
        - "3000:3000"
     networks:
        - mern-app
   api-server:
     image: api-server
     ports: 
        - "8080:8080"
     networks:
        - mern-app
     depends_on:
        - mongo
   mongo:
      image: mongo
      ports: 
        - "27017:27017" 
      networks:
        - mern-app
      volumes:
        - mongo-data:/data/db

networks:
   mern-app:
     driver: bridge
volumes:
   mongo-data:
     driver: local